Stool service
ProtocolONE/cord.stool pull request #7
Opened 2019-01-09 09:59 UTC by Clipeus

2019-01-24 11:17 UTC, Clipeus commented on cmd/cmd.go
> +	"cord.stool/cmd/service"
Test

2019-01-25 10:59 UTC, misterion commented on cordapi/cordapi.go
> +	res, err := utils.Post(host + "/api/v1/cmd/upload", token, "application/json", bytes.NewBuffer(data))
test

2019-01-25 11:20 UTC, misterion requested changes

2019-01-25 11:20 UTC, misterion commented on utils/utils.go
> +	return client.Do(req)
Вы тут осознанно возвращаете не прочитанный ответ а объект запроса, который потом нужно руками вычитывать? Если да, зачем.

2019-01-25 11:20 UTC, misterion commented on service/routers/cmd.go
> +    e.POST("/api/v1/cmd/upload", controllers.UploadCmd)
Зачем cmd в пути? Ведь тут по сути 

/api/v1/files/upload
/api/v1/files/computeHash

2019-01-25 11:20 UTC, misterion commented on service/routers/auth.go
> +    /*router.Handle(
мусор

2019-01-25 11:20 UTC, misterion commented on cmd/cmd.go
>  	"cord.stool/cmd/torrent"
По всему проекту:
- gofmt. куча мест с поехавшим форматированием!
- везде ошибки возвращаются в виде, который сложно поддерживать - строкой. Должно быть объект {error_code ..., error_message}
- везде возврат ошибок от балды (http.StatusInternalServerError). Используйте конкретные ощибки в зависимости от контекста

2019-01-25 11:20 UTC, misterion commented on upload/cord/cord.go
> +var _bar *uiprogress.Bar
Почему это глобальная переменная?

2019-01-25 11:20 UTC, misterion commented on service/routers/auth.go
> +    e.POST("/api/v1/token-auth", controllers.Login)
/api/v1/token-auth -> /api/v1/auth/token
/api/v1/refresh-token-auth -> /api/v1/auth/refreshToken

2019-01-25 11:20 UTC, misterion commented on service/database/database.go
> +func GeUserManager() (*UserManager) {
Так не принято в go.
GeUserManager -> newUserManager

2019-01-25 11:20 UTC, misterion commented on service/core/utils/utils.go
> +	users, err := manager.FindByName(clientID)
Как это возможно? Такого не должно быть - вставка должна проверяться на этапе добавления.

2019-01-25 11:20 UTC, misterion commented on service/core/authentication/middlewares.go
> +		//context.Echo().Logger.Info("req token %s", req.Header.Get("Authorization"))
мусор

2019-01-25 11:20 UTC, misterion commented on service/controllers/cmd.go
> +	if !authentication.RequireTokenAuthentication(context) {
Это не удачная конструкция для проверки авторизации - используйте Midleware. Пример можно посмотреть в платежном проекте

2019-01-25 11:20 UTC, misterion commented on service/controllers/auth.go
> +func RefreshToken(context echo.Context) error {
Я нигде в коде не нахожу логики рефреша в случае, если мой запрос пройдет со старым токеном.

2019-01-25 11:20 UTC, misterion commented on cordapi/cordapi.go
> +	cmpRes := new(models.CompareHashCmdResult)
Тут написано странное. в echo есть Bind который позволяет сразу анмаршалить объекты

2019-01-25 11:20 UTC, misterion commented on cordapi/cordapi.go
> +	decoder := json.NewDecoder(res.Body)
Тут написано странное. в echo есть Bind который позволяет сразу анмаршалить объекты

2019-01-25 11:20 UTC, misterion commented on utils/utils.go
> +func Post(url, token string, contentType string, body io.Reader) (resp *http.Response, err error) {
Зачем вы принимаете тут body io.Reader на вход? Вы везде по коду кидаете сюда объекты - передавайте объекты через obj *interface{} и сериализуйте тут

2019-01-30 07:49 UTC, misterion requested changes

2019-01-30 07:49 UTC, misterion commented on cordapi/cordapi.go
> +func NewCordAPI(host string) *CordAPIManager {
Возвращаться должен CordAPI , а CordAPIManager  быть приватным

2019-01-30 07:49 UTC, misterion commented on cordapi/cordapi.go
> +	if err != nil {
Короткие возвраты! Проще!
```
if err == nil {
    return err
}

if sc != http.StatusUnauthorized {
     return err
}

...
```
Актуально тут и далее по коду

2019-01-30 07:49 UTC, misterion commented on cordapi/cordapi.go
> +		errorRes := new(models.Error)
Эти 10 строк у вас дублируются как минимум в 4 местах - перепишите на вызов вспомогательного метода

2019-01-30 07:49 UTC, misterion commented on service/controllers/auth.go
> +		return echo.NewHTTPError(http.StatusInternalServerError, fmt.Sprintf("Cannot read from database, error: %s", err.Error()))
Нет! StatusInternalServerError (500) это реальное падение на сервере. Тут вы просто не нашли пользователя - возвращайте корректные коды ошибок. Отправляйтесь с спецификации свагера по килину, авторизации или платежке чтобы понять разницу. Посоветуйтесь с Вадимом, Димой или Романом.

2019-01-30 07:49 UTC, misterion commented on service/controllers/auth.go
> +		return echo.NewHTTPError(http.StatusInternalServerError, fmt.Sprintf("User %s already exists", reqUser.Username))
см. выше

2019-01-31 08:57 UTC, misterion requested changes

2019-01-31 08:57 UTC, misterion commented on service/controllers/auth.go
> +	zap.S().Infof("Created new user %s.", reqUser.Username)
Это не верно! Такой формат логов не даст вам корректный json на выходе. Должно быть 
```
zap.S().Info("Created new user", "username", reqUser.Username)
```
или 
```
logger.Info("Created new user", zap.String("username", reqUser.Username))
```

2019-01-31 08:57 UTC, misterion commented on service/core/authentication/middlewares.go
> +				zap.S().Error(err.Error())
Не делайте так! Как вы поймете что именно за ошибка и где она произошла?

2019-01-31 08:57 UTC, misterion commented on service/core/authentication/middlewares.go
> +				zap.S().Error("Authorization failed")
Не делайте так. Какой вывод из логов можно сделать? У кого авторизация не прошла? Почему?

2019-01-31 08:57 UTC, misterion commented on service/service.go
> +	zap.S().Info(fmt.Sprintf("Create service. Scheme: %s, port: %d", conf.Service.HttpScheme, conf.Service.ServicePort))
НЕ ДЕЛАЙТЕ ТАК!!!

2019-02-01 11:23 UTC, misterion approved these changes

2019-02-01 11:23 UTC, merged